# Generated by Django 6.0.2 on 2026-02-14 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment",
            new_name="payment_provider",
        ),
    ]
