# Generated by Django 6.0.2 on 2026-02-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_order_payment_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intend_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
